// src/components/form/auth/signupForm.tsx
'use client';
import { ChangeEvent, useEffect, useState } from 'react';
import styles from './auth-form.module.scss';
import EyeIcon from '@/assets/icons/eye.svg';
import CloseEyeIcon from '@/assets/icons/close-eye.svg';
import LockIcon from '@/assets/icons/lock.svg';
import MailIcon from '@/assets/icons/mail.svg';
import CommonButton from '@/components/common/buttons/common-button';
import CheckIcon from '@/assets/active-icon/check-active.svg';
import Image from 'next/image';
import { PasswordRuleType } from '@/data/type';

export default function SignUpForm() {
  // 비밀번호 보기
  const [showPassword, setShowPassword] = useState<Boolean | null>(null);
  const [showPasswordConfirm, setShowPasswordConfirm] =
    useState<Boolean | null>(null);
  const [signupData, setSignupData] = useState({
    email: '',
    password: '',
    password_confirm: '',
    nickname: '',
  });
  // state 변경 시 재렌더링되기 때문에 useEffect 불필요
  // 비밀번호 확인 파트
  const passwordRules = {
    length: signupData.password.length >= 8,
    english: /[A-Za-z]/.test(signupData.password),
    number: /\d/.test(signupData.password),
    special: /[!@#$%^&*(),.?":{}|<>]/.test(signupData.password),
  };

  const passedCount = Object.values(passwordRules).filter(Boolean).length;

  const strengthClass =
    passedCount === 4
      ? styles.strong
      : passedCount >= 2
        ? styles.medium
        : styles.weak;

  const passwordCheckList: {
    type: PasswordRuleType;
    label: string;
  }[] = [
    { type: 'length', label: '8자 이상' },
    { type: 'english', label: '영문 포함' },
    { type: 'number', label: '숫자 포함' },
    { type: 'special', label: '특수문자 포함' },
  ];

  // 비밀번호 확인파트 종료
  const handleOnChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { id, value } = e.target;
    setSignupData({ ...signupData, [id]: value });
  };

  useEffect(() => {
    setShowPassword(false);
    setShowPasswordConfirm(false);
  }, []);

  return (
    <form className={styles.form} onSubmit={() => {}}>
      <div className={styles.formData}>
        <label htmlFor="id">닉네임</label>
        <div className={styles.formInput}>
          <span className="span-image">
            <Image fill src={MailIcon.src} alt="nickname" />
          </span>
          <input
            type="text"
            id="nickname"
            value={signupData.nickname}
            onChange={(e) => handleOnChange(e)}
          />
        </div>
      </div>
      <div className={styles.formData}>
        <label htmlFor="id">이메일</label>
        <div className={styles.formInput}>
          <span className="span-image">
            <Image fill src={MailIcon.src} alt="email" />
          </span>
          <input
            type="text"
            id="email"
            value={signupData.email}
            onChange={(e) => handleOnChange(e)}
          />
        </div>
      </div>
      <div className={styles.formData}>
        <label htmlFor="password">비밀번호</label>
        <div className={styles.formInput}>
          <span className="span-image">
            <Image fill src={LockIcon.src} alt="lock" />
          </span>
          <input
            type={showPassword ? 'text' : 'password'}
            id="password"
            value={signupData.password}
            onChange={(e) => handleOnChange(e)}
          />
          <button
            type="button"
            className={styles.showPassword}
            onClick={() => setShowPassword(!showPassword)}
          >
            {showPassword ? (
              <Image fill src={EyeIcon.src} alt="eye" />
            ) : (
              <Image fill src={CloseEyeIcon.src} alt="close-eye" />
            )}
          </button>
        </div>
        {signupData.password.length > 0 && (
          <>
            <div className={styles.passwordStrength}>
              {[1, 2, 3, 4].map((item) => (
                <div
                  key={item}
                  className={`${styles.strengthBar} ${passedCount >= item ? strengthClass : ''}`}
                />
              ))}
            </div>
            <ul className={styles.passwordChackList}>
              {passwordCheckList.map((data) => {
                return (
                  <li
                    className={`${
                      passwordRules[data.type] ? styles.active : styles.discard
                    }
                     ${styles.passwordChacklabel}`}
                  >
                    <CheckIcon /> {data.label}
                  </li>
                );
              })}
            </ul>
          </>
        )}
      </div>
      <div className={styles.formData}>
        <label htmlFor="password">비밀번호 확인</label>
        <div className={styles.formInput}>
          <span className="span-image">
            <Image fill src={LockIcon.src} alt="lock" />
          </span>
          <input
            type={showPasswordConfirm ? 'text' : 'password'}
            id="password_confirm"
            value={signupData.password_confirm}
            onChange={(e) => handleOnChange(e)}
          />
          <button
            type="button"
            className={styles.showPassword}
            onClick={() => setShowPasswordConfirm(!showPasswordConfirm)}
          >
            {showPasswordConfirm ? (
              <Image fill src={EyeIcon.src} alt="eye" />
            ) : (
              <Image fill src={CloseEyeIcon.src} alt="close-eye" />
            )}
          </button>
        </div>
        {signupData.password_confirm.length > 0 &&
          signupData.password.length > 0 && (
            <div
              className={`${
                signupData.password === signupData.password_confirm
                  ? styles.active
                  : styles.discard
              }
            ${styles.passwordChacklabel}`}
            >
              <CheckIcon />
              <p>비밀번호가 일치합니다.</p>
            </div>
          )}
      </div>
      <CommonButton variant="gradient-shadow" text="회원가입" type="submit" />
    </form>
  );
}

// src/components/form/auth/SignupForm.vue
<script setup lang="ts">
import { computed } from 'vue'
import AuthInputField from '@/components/form/auth/AuthInputField.vue'
import CommonButton from '@/components/common/CommonButton.vue'
import { PASSWORD_CHECK_LIST } from '@/composables/usePasswordValidation'
import { useSignupForm } from '@/composables/useSignupForm'
import CheckActiveIcon from '@/assets/icons/check-active.svg?component'
import mailIcon from '@/assets/icons/mail.svg'
import lockIcon from '@/assets/icons/lock.svg'
import eyeIcon from '@/assets/icons/eye.svg'
import closeEyeIcon from '@/assets/icons/close-eye.svg'
import userIcon from '@/assets/icons/user-icon.svg'

const {
  signupData,
  signupError,
  showPassword,
  showPasswordConfirm,
  passedCount,
  passwordRules,
  strengthLevel,
  isSubmitting,
  updateField,
  togglePasswordVisibility,
  togglePasswordConfirmVisibility,
  handleSubmit,
} = useSignupForm()

const strengthClass = computed(() => ({
  'auth-form__strength-bar--strong': strengthLevel.value === 'strong',
  'auth-form__strength-bar--medium': strengthLevel.value === 'medium',
  'auth-form__strength-bar--weak': strengthLevel.value === 'weak',
}))

const passwordsMatch = computed(
  () =>
    signupData.password.length > 0 &&
    signupData.password_confirm.length > 0 &&
    signupData.password === signupData.password_confirm,
)
</script>

<template>
  <form class="auth-form" @submit.prevent="handleSubmit">
    <AuthInputField
      id="nickname"
      label="이름"
      :icon="userIcon"
      type="text"
      placeholder="홍길동"
      autocomplete="name"
      :model-value="signupData.nickname"
      :error="signupError.nickname"
      @update:model-value="updateField('nickname', $event)"
    />

    <AuthInputField
      id="email"
      label="이메일"
      :icon="mailIcon"
      type="email"
      placeholder="example@email.com"
      autocomplete="email"
      :model-value="signupData.email"
      :error="signupError.email"
      @update:model-value="updateField('email', $event)"
    />

    <div class="auth-form__field-group">
      <AuthInputField
        id="password"
        label="비밀번호"
        :icon="lockIcon"
        :type="showPassword ? 'text' : 'password'"
        placeholder="8자 이상 입력"
        autocomplete="new-password"
        show-toggle
        :visible="showPassword"
        :model-value="signupData.password"
        :error="signupError.password"
        @update:model-value="updateField('password', $event)"
        @toggle-visibility="togglePasswordVisibility"
      >
        <template #toggle-icon>
          <img :src="showPassword ? eyeIcon : closeEyeIcon" alt="" width="15" height="15" />
        </template>
      </AuthInputField>

      <template v-if="signupData.password.length > 0">
        <div class="auth-form__strength">
          <div
            v-for="item in 4"
            :key="item"
            class="auth-form__strength-bar"
            :class="passedCount >= item ? strengthClass : undefined"
          />
        </div>

        <ul class="auth-form__check-list">
          <li
            v-for="rule in PASSWORD_CHECK_LIST"
            :key="rule.type"
            class="auth-form__check-item"
            :class="
              passwordRules[rule.type]
                ? 'auth-form__check-item--active'
                : 'auth-form__check-item--inactive'
            "
          >
            <CheckActiveIcon class="auth-form__check-icon" aria-hidden="true" />
            {{ rule.label }}
          </li>
        </ul>
      </template>
    </div>

    <div class="auth-form__field-group">
      <AuthInputField
        id="password_confirm"
        label="비밀번호 확인"
        :icon="lockIcon"
        :type="showPasswordConfirm ? 'text' : 'password'"
        placeholder="비밀번호 재입력"
        autocomplete="new-password"
        show-toggle
        :visible="showPasswordConfirm"
        :success="passwordsMatch"
        :model-value="signupData.password_confirm"
        :error="signupError.password_confirm"
        @update:model-value="updateField('password_confirm', $event)"
        @toggle-visibility="togglePasswordConfirmVisibility"
      >
        <template #toggle-icon>
          <img
            :src="showPasswordConfirm ? eyeIcon : closeEyeIcon"
            alt=""
            width="15"
            height="15"
          />
        </template>
      </AuthInputField>

      <div
        v-if="passwordsMatch"
        class="auth-form__match auth-form__check-item auth-form__check-item--active"
      >
        <CheckActiveIcon class="auth-form__check-icon" aria-hidden="true" />
        <span>비밀번호가 일치합니다</span>
      </div>
    </div>

    <CommonButton
      variant="gradient-shadow"
      text="회원가입"
      type="submit"
      class="auth-form__submit"
      :disabled="isSubmitting"
    />
  </form>
</template>

<style scoped>
.auth-form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.auth-form__field-group {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.auth-form__strength {
  display: flex;
  gap: 0.25rem;
  width: 100%;
}

.auth-form__strength-bar {
  flex: 1;
  height: 0.25rem;
  border-radius: 50rem;
  background-color: var(--line-component-background-color);
}

.auth-form__strength-bar--strong {
  background-color: #00d492;
}

.auth-form__strength-bar--medium {
  background-color: #ff8904;
}

.auth-form__strength-bar--weak {
  background-color: #fb2c36;
}

.auth-form__check-list {
  display: flex;
  justify-content: space-between;
  gap: 0.25rem;
  margin: 0;
  padding: 0;
  list-style: none;
}

.auth-form__check-item {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  font-size: var(--font-size-caption);
}

.auth-form__check-icon {
  flex-shrink: 0;
  width: 0.6875rem;
  height: 0.6875rem;
}

.auth-form__check-item--active {
  color: #00d492;
}

.auth-form__check-item--active .auth-form__check-icon {
  color: #00d492;
}

.auth-form__check-item--inactive {
  color: var(--caption-text-color);
}

.auth-form__check-item--inactive .auth-form__check-icon {
  color: var(--caption-text-color);
}

.auth-form__match {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  font-size: var(--font-size-caption);
}

.auth-form__submit {
  width: 100%;
  margin-top: 1.5rem;
}

.auth-form__submit :deep(.common-button) {
  width: 100%;
}
</style>
